import { getDataset } from '../../content/datasets/company';
import { runQuery } from '../sqlEngine';
import { compareResults } from '../validate';
import { askMentor } from './index';
import type { AiConfig, LearnerProfile } from './types';
import type { Difficulty, PracticeQuestion } from '../../types';

// AI question generation is only as trustworthy as its validation. A generated
// question is accepted only if its solution runs against the real database,
// returns columns, and is deterministic (the same query run twice agrees). This
// guarantees we never present a learner with a broken or ambiguous question.

export interface GenerateResult {
  ok: boolean;
  question?: PracticeQuestion;
  reason?: string;
}

function extractJson(text: string): unknown {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

export async function generateQuestion(
  config: AiConfig,
  profile: LearnerProfile,
  opts: { difficulty: Difficulty; datasetId?: string }
): Promise<GenerateResult> {
  const datasetId = opts.datasetId ?? 'company';
  const dataset = getDataset(datasetId);

  const prompt = [
    'Generate one original SQL practice question for the following SQLite schema.',
    'Return ONLY JSON with keys: statement, solution, orderMatters (boolean).',
    'The solution must be a single read-only SELECT that runs against the schema.',
    `Difficulty: ${opts.difficulty}.`,
    '',
    'Schema (CREATE statements):',
    dataset.seedSql.split('INSERT')[0].trim(),
  ].join('\n');

  const { text, provider } = await askMentor(
    config,
    [{ role: 'user', content: prompt }],
    { task: 'chat', profile }
  );

  // The offline provider cannot author novel, verified SQL, so generation needs
  // a hosted model. Be explicit rather than returning something unverified.
  if (provider === 'offline') {
    return { ok: false, reason: 'Add an AI key in settings to generate new questions.' };
  }

  const parsed = extractJson(text) as
    | { statement?: string; solution?: string; orderMatters?: boolean }
    | null;
  if (!parsed?.statement || !parsed?.solution) {
    return { ok: false, reason: 'The model did not return a usable question.' };
  }

  const first = await runQuery(datasetId, dataset.seedSql, parsed.solution);
  if (!first.ok || !first.result || first.result.columns.length === 0) {
    return { ok: false, reason: 'The generated solution did not run, so it was rejected.' };
  }
  const second = await runQuery(datasetId, dataset.seedSql, parsed.solution);
  if (!second.ok || !second.result) {
    return { ok: false, reason: 'The generated solution was not reproducible, so it was rejected.' };
  }
  if (!compareResults(first.result, second.result, false).correct) {
    return { ok: false, reason: 'The generated solution was non-deterministic, so it was rejected.' };
  }

  const question: PracticeQuestion = {
    id: `ai-${Date.now()}`,
    difficulty: opts.difficulty,
    datasetId,
    statement: parsed.statement,
    hints: ['Generated by the AI mentor and validated against the database.'],
    solution: parsed.solution,
    orderMatters: Boolean(parsed.orderMatters),
    expected: first.result,
  };
  return { ok: true, question };
}
